name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_VERSION: 8.2
      ANDROID_SDK_VERSION: "34"
      API_LEVEL: 34
      BUILD_TOOLS_VERSION: "34.0.0"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip gradle-8.2-bin.zip
        export PATH=$PATH:$PWD/gradle-8.2/bin

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        build-tools: ${{ env.BUILD_TOOLS_VERSION }}
        ndk: true

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-${{ runner.os }}

    - name: Download dependencies
      run: gradle build --no-daemon

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Run unit tests
      run: gradle testDebugUnitTest

    - name: Start the emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: default
        arch: x86_64
        profile: Nexus 6
        emulator-options: -no-window -no-audio -no-boot-anim
        cores: 2
        avd-name: test
        force-avd-creation: true
        emulator-boot-timeout: 600
        emulator-port: 5554
        disable-animations: true
        disable-spellchecker: false
        disable-linux-hw-accel: true
        enable-hw-keyboard: false
        channel: stable

    - name: Wait for emulator to boot
      run: adb wait-for-device

    - name: Run instrumented tests
      run: gradle connectedAndroidTest

    - name: Verify emulator is running
      run: adb shell getprop init.svc.bootanim

    - name: Archive build outputs
      if: failure() # Only archive if the build fails
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: |
          app/build/outputs/mapping/release/missing_rules.txt
          app/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt
